/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package absen.karyawan.ui.panel;

import absen.karyawan.Main;
import absen.karyawan.TableUtil;
import absen.karyawan.dialog.KaryawanDialog;
import absen.karyawan.domain.Absensi;
import absen.karyawan.domain.Karyawan;
import absen.karyawan.domain.PenilaianDTO;
import absen.karyawan.domain.Point;
import absen.karyawan.tablemodel.RekapHarianTableModel;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author adi
 */
public class PenilaianPanel extends javax.swing.JPanel {

    private static PenilaianPanel panel;
    public static final String PANEL_NAME = "Penilaian";
    private List<Karyawan> karyawans;
    private Karyawan karyawanSearch;
    private Karyawan karyawanAbsensi;
    private Karyawan karyawanPoint;

    public static PenilaianPanel getPanel() {
        if(panel==null){
            panel = new PenilaianPanel();
        }
        return panel;
    }
    /**
     * Creates new form PenilaianPanel
     */
    public PenilaianPanel() {
        try {
            initComponents();
            jDateChooser1.setDate(new Date());
            karyawanAbsensi = null;
            karyawanSearch = null;
            karyawanPoint = null;
            karyawans = Main.getService().getAllKaryawan();
            
            tblPenilaian.setModel(new RekapHarianTableModel(new ArrayList<PenilaianDTO>()));
            TableUtil.initColumn(tblPenilaian);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(Main.getMainFrame(), ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtKaryawanAbsensi = new javax.swing.JTextField();
        checkHadir = new javax.swing.JCheckBox();
        btnBatalAbsensi = new javax.swing.JButton();
        btnSimpanAbsensi = new javax.swing.JButton();
        btnLookupKaryawan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKaryawanPoint = new javax.swing.JTextField();
        btnBatalPoint = new javax.swing.JButton();
        btnSimpanPoint = new javax.swing.JButton();
        btnLookupKaryawan1 = new javax.swing.JButton();
        txtPointKaryawan = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPenilaian = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtSearchKaryawan = new javax.swing.JTextField();
        btnSearchKaryawan = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cmbSearchOption = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        dateDariTanggal = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        dateSampaiTanggal = new com.toedter.calendar.JDateChooser();
        btnSearchAction = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Absensi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jLabel2.setText("Karyawan");

        jLabel3.setText("Hadir");

        txtKaryawanAbsensi.setEnabled(false);

        checkHadir.setText("Ya");

        btnBatalAbsensi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absen/karyawan/images/reload.png"))); // NOI18N
        btnBatalAbsensi.setText("Batal");
        btnBatalAbsensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalAbsensiActionPerformed(evt);
            }
        });

        btnSimpanAbsensi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absen/karyawan/images/save.png"))); // NOI18N
        btnSimpanAbsensi.setText("Simpan");
        btnSimpanAbsensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanAbsensiActionPerformed(evt);
            }
        });

        btnLookupKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absen/karyawan/images/lookup_icon.gif"))); // NOI18N
        btnLookupKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLookupKaryawanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKaryawanAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkHadir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLookupKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSimpanAbsensi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatalAbsensi)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBatalAbsensi, btnSimpanAbsensi});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKaryawanAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLookupKaryawan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(checkHadir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanAbsensi)
                    .addComponent(btnBatalAbsensi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnLookupKaryawan, jLabel2, txtKaryawanAbsensi});

        jLabel1.setText("Tanggal");

        jDateChooser1.setEnabled(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Point", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jLabel4.setText("Karyawan");

        jLabel5.setText("Hadir");

        txtKaryawanPoint.setEnabled(false);

        btnBatalPoint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absen/karyawan/images/reload.png"))); // NOI18N
        btnBatalPoint.setText("Batal");
        btnBatalPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalPointActionPerformed(evt);
            }
        });

        btnSimpanPoint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absen/karyawan/images/save.png"))); // NOI18N
        btnSimpanPoint.setText("Simpan");
        btnSimpanPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanPointActionPerformed(evt);
            }
        });

        btnLookupKaryawan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absen/karyawan/images/lookup_icon.gif"))); // NOI18N
        btnLookupKaryawan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLookupKaryawan1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKaryawanPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLookupKaryawan1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnSimpanPoint)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBatalPoint))
                            .addComponent(txtPointKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel4, jLabel5});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKaryawanPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLookupKaryawan1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPointKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanPoint)
                    .addComponent(btnBatalPoint))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnLookupKaryawan1, txtKaryawanPoint});

        tblPenilaian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPenilaian.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(tblPenilaian);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absen/karyawan/images/logout.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Karyawan");

        txtSearchKaryawan.setEnabled(false);

        btnSearchKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absen/karyawan/images/lookup_icon.gif"))); // NOI18N
        btnSearchKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchKaryawanActionPerformed(evt);
            }
        });

        jLabel7.setText("Jenis Data");

        cmbSearchOption.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SEMUA", "ABSENSI", "POINT" }));

        jLabel8.setText("Dari Tanggal");

        jLabel9.setText("s/d");

        btnSearchAction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absen/karyawan/images/refresh.gif"))); // NOI18N
        btnSearchAction.setText("Cari");
        btnSearchAction.setFocusable(false);
        btnSearchAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearchKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchKaryawan)
                .addGap(35, 35, 35)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbSearchOption, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateDariTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateSampaiTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchAction)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jLabel6)
                .addComponent(txtSearchKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnSearchKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel7)
                .addComponent(cmbSearchOption, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel8)
                .addComponent(dateDariTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel9)
                .addComponent(dateSampaiTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnSearchAction, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSearchAction, btnSearchKaryawan, cmbSearchOption, dateDariTanggal, dateSampaiTanggal, jLabel6, jLabel7, jLabel8, jLabel9, txtSearchKaryawan});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jDateChooser1, jLabel1});

    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalAbsensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalAbsensiActionPerformed
        karyawanAbsensi = null;
        txtKaryawanAbsensi.setText("");
        checkHadir.setSelected(false);
    }//GEN-LAST:event_btnBatalAbsensiActionPerformed

    private void btnSimpanAbsensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanAbsensiActionPerformed
        if(karyawanAbsensi!=null){
            try {
                Absensi abs = new Absensi();
                abs.setKaryawan(karyawanAbsensi);
                abs.setTanggal(new Date());
                abs.setHadir(checkHadir.isSelected());
                Main.getService().simpan(abs);
                btnBatalAbsensiActionPerformed(evt);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(Main.getMainFrame(), ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(Main.getMainFrame(), "karyawan absensi tidak boleh null", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpanAbsensiActionPerformed

    private void btnLookupKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLookupKaryawanActionPerformed
        karyawanAbsensi = new KaryawanDialog().showDialog();
        if(karyawanAbsensi != null){
            txtKaryawanAbsensi.setText(karyawanAbsensi.getNip() + '-' + karyawanAbsensi.getNama());
        } else {
            txtKaryawanAbsensi.setText("");
        }
    }//GEN-LAST:event_btnLookupKaryawanActionPerformed

    private void btnLookupKaryawan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLookupKaryawan1ActionPerformed
        karyawanPoint = new KaryawanDialog().showDialog();
        if(karyawanPoint != null){
            txtKaryawanPoint.setText(karyawanPoint.getNip() + '-' + karyawanPoint.getNama());
        } else {
            txtKaryawanPoint.setText("");
        }
    }//GEN-LAST:event_btnLookupKaryawan1ActionPerformed

    private void btnBatalPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalPointActionPerformed
        karyawanPoint = null;
        txtKaryawanPoint.setText("");
        txtPointKaryawan.setText("");
    }//GEN-LAST:event_btnBatalPointActionPerformed

    private void btnSimpanPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanPointActionPerformed
        if(karyawanPoint!=null){
            try {
                Point p = new Point();
                p.setKaryawan(karyawanPoint);
                p.setTanggal(new Date());
                p.setPoint(new Integer(txtPointKaryawan.getText()));
                Main.getService().simpan(p);
                btnBatalPointActionPerformed(evt);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(Main.getMainFrame(), ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(Main.getMainFrame(), "karyawan point tidak boleh null", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpanPointActionPerformed

    private void btnSearchActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionActionPerformed
        if(dateDariTanggal.getDate()==null || dateSampaiTanggal.getDate()==null){
            JOptionPane.showMessageDialog(Main.getMainFrame(), "Range tanggal harus diisi !!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String sdate = sdf.format(dateDariTanggal.getDate());
        String edate = sdf.format(dateSampaiTanggal.getDate());
        
        List<PenilaianDTO> dtos = new ArrayList<PenilaianDTO>();
        try {
            if(karyawanSearch != null){
                if(cmbSearchOption.getSelectedItem().equals("ABSENSI")){
                    dtos = Main.getService().hitungRekapAbsensi(karyawanSearch, sdate, edate);
                } else if(cmbSearchOption.getSelectedItem().equals("POINT")) {
                    dtos = Main.getService().hitungRekapPoint(karyawanSearch, sdate, edate);
                } else {
                    dtos = Main.getService().hitungRekapAll(karyawanSearch, sdate, edate);
                }
            } else {
                if(cmbSearchOption.getSelectedItem().equals("ABSENSI")){
                    dtos = Main.getService().hitungRekapAbsensi(sdate, edate);
                } else if(cmbSearchOption.getSelectedItem().equals("POINT")) {
                    dtos = Main.getService().hitungRekapPoint(sdate, edate);
                } else {
                    dtos = Main.getService().hitungRekapAll(sdate, edate);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(Main.getMainFrame(), ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        tblPenilaian.setModel(new RekapHarianTableModel(dtos));
        TableUtil.initColumn(tblPenilaian);
    }//GEN-LAST:event_btnSearchActionActionPerformed

    private void btnSearchKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchKaryawanActionPerformed
        karyawanSearch = new KaryawanDialog().showDialog();
        if(karyawanSearch != null){
            txtSearchKaryawan.setText(karyawanSearch.getNip() + '-' + karyawanSearch.getNama());
        } else {
            txtSearchKaryawan.setText("");
        }
    }//GEN-LAST:event_btnSearchKaryawanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Main.getMainFrame().getTabPanel().remove(this);
        panel=null;
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalAbsensi;
    private javax.swing.JButton btnBatalPoint;
    private javax.swing.JButton btnLookupKaryawan;
    private javax.swing.JButton btnLookupKaryawan1;
    private javax.swing.JButton btnSearchAction;
    private javax.swing.JButton btnSearchKaryawan;
    private javax.swing.JButton btnSimpanAbsensi;
    private javax.swing.JButton btnSimpanPoint;
    private javax.swing.JCheckBox checkHadir;
    private javax.swing.JComboBox cmbSearchOption;
    private com.toedter.calendar.JDateChooser dateDariTanggal;
    private com.toedter.calendar.JDateChooser dateSampaiTanggal;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblPenilaian;
    private javax.swing.JTextField txtKaryawanAbsensi;
    private javax.swing.JTextField txtKaryawanPoint;
    private javax.swing.JTextField txtPointKaryawan;
    private javax.swing.JTextField txtSearchKaryawan;
    // End of variables declaration//GEN-END:variables
}
