/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package absen.karyawan.ui;

import absen.karyawan.Main;
import absen.karyawan.ui.panel.GenerateRekapPanel;
import absen.karyawan.ui.panel.JabatanPanel;
import absen.karyawan.ui.panel.KaryawanPanel;
import absen.karyawan.ui.panel.ManagementPanel;
import absen.karyawan.ui.panel.PenilaianPanel;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JTabbedPane;

/**
 *
 * @author adi
 */
public class MainFrame extends javax.swing.JFrame {

    private Integer indexTab = -1;
    private static Map<String, String> dataUser = new HashMap<String, String>();
    private String userLogin;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(MainFrame.MAXIMIZED_BOTH);
    }

    public void setUserLogin(String userLogin) {
        this.userLogin = userLogin;
    }
    
    public void isiMapUser(){
        dataUser.put("supervisor", "spv123");
        dataUser.put("hrd", "hrd123");
        dataUser.put("pimpinan", "boss123");
    }
    
    public void  initSecurity(){
        disableAllMenu();
        if(userLogin.equals("supervisor")){
            mnuPenilaian.setVisible(true);
            mnuItemInputPenilaian.setVisible(true);
        } else if(userLogin.equals("hrd")){
            mnuData.setVisible(true);
            mnuPenilaian.setVisible(true);
            mnuItemKaryawan.setVisible(true);
            mnuItemJabatan.setVisible(true);
            mnuItemRekapPenilaian.setVisible(true);
        } else {
            mnuPenilaian.setVisible(true);
            mnuItemManagement.setVisible(true);
        }
    }
    
    private void disableAllMenu(){
        mnuItemKaryawan.setVisible(false);
        mnuItemJabatan.setVisible(false);
        mnuItemInputPenilaian.setVisible(false);
        mnuItemRekapPenilaian.setVisible(false);
        mnuItemManagement.setVisible(false);
        mnuData.setVisible(false);
        mnuPenilaian.setVisible(false);
    }

    public Boolean login(String user, String password) {
        String pass = dataUser.get(user);
        if(pass==null){
            return false;
        } else if(pass.equals(password)){
            return true;
        } else {
            return false;
        }
    }
    
    public JTabbedPane getTabPanel() {
        return tabPanel;
    }
    
    private int getComponentIndexByName(String panelName) {
        return tabPanel.indexOfTab(panelName);
    }

    private void setSelectedPanel(String panelName) {
        tabPanel.setSelectedComponent(tabPanel.getComponentAt(getComponentIndexByName(panelName)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tabPanel = new javax.swing.JTabbedPane();
        jImagePanel1 = new absen.karyawan.ui.JImagePanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuItemLogout = new javax.swing.JMenuItem();
        mnuData = new javax.swing.JMenu();
        mnuItemKaryawan = new javax.swing.JMenuItem();
        mnuItemJabatan = new javax.swing.JMenuItem();
        mnuPenilaian = new javax.swing.JMenu();
        mnuItemInputPenilaian = new javax.swing.JMenuItem();
        mnuItemRekapPenilaian = new javax.swing.JMenuItem();
        mnuItemManagement = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Penilaian Karyawan");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RANCANGAN APLIKASI AHP");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PENILAIAN KARYAWAN di PT. X");

        javax.swing.GroupLayout jImagePanel1Layout = new javax.swing.GroupLayout(jImagePanel1);
        jImagePanel1.setLayout(jImagePanel1Layout);
        jImagePanel1Layout.setHorizontalGroup(
            jImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );
        jImagePanel1Layout.setVerticalGroup(
            jImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );

        tabPanel.addTab("Home", jImagePanel1);

        jMenu1.setText("System");

        mnuItemLogout.setText("Logout");
        mnuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(mnuItemLogout);

        jMenuBar1.add(jMenu1);

        mnuData.setText("Data");

        mnuItemKaryawan.setText("Karyawan");
        mnuItemKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemKaryawanActionPerformed(evt);
            }
        });
        mnuData.add(mnuItemKaryawan);

        mnuItemJabatan.setText("Jabatan");
        mnuItemJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemJabatanActionPerformed(evt);
            }
        });
        mnuData.add(mnuItemJabatan);

        jMenuBar1.add(mnuData);

        mnuPenilaian.setText("Penilaian");

        mnuItemInputPenilaian.setText("Input Penilaian");
        mnuItemInputPenilaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemInputPenilaianActionPerformed(evt);
            }
        });
        mnuPenilaian.add(mnuItemInputPenilaian);

        mnuItemRekapPenilaian.setText("Rekap Penilaian");
        mnuItemRekapPenilaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemRekapPenilaianActionPerformed(evt);
            }
        });
        mnuPenilaian.add(mnuItemRekapPenilaian);

        mnuItemManagement.setText("Management");
        mnuItemManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemManagementActionPerformed(evt);
            }
        });
        mnuPenilaian.add(mnuItemManagement);

        jMenuBar1.add(mnuPenilaian);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPanel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemKaryawanActionPerformed
        KaryawanPanel.getPanel().setName(KaryawanPanel.PANEL_NAME);
        indexTab = getComponentIndexByName(KaryawanPanel.PANEL_NAME);
        if (indexTab == -1) {
            tabPanel.addTab(KaryawanPanel.PANEL_NAME, KaryawanPanel.getPanel());
            setSelectedPanel(KaryawanPanel.PANEL_NAME);
        } else {
            tabPanel.setSelectedIndex(indexTab);
        }
    }//GEN-LAST:event_mnuItemKaryawanActionPerformed

    private void mnuItemJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemJabatanActionPerformed
        JabatanPanel.getPanel().setName(JabatanPanel.PANEL_NAME);
        indexTab = getComponentIndexByName(JabatanPanel.PANEL_NAME);
        if (indexTab == -1) {
            tabPanel.addTab(JabatanPanel.PANEL_NAME, JabatanPanel.getPanel());
            setSelectedPanel(JabatanPanel.PANEL_NAME);
        } else {
            tabPanel.setSelectedIndex(indexTab);
        }
    }//GEN-LAST:event_mnuItemJabatanActionPerformed

    private void mnuItemInputPenilaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemInputPenilaianActionPerformed
        PenilaianPanel.getPanel().setName(PenilaianPanel.PANEL_NAME);
        indexTab = getComponentIndexByName(PenilaianPanel.PANEL_NAME);
        if (indexTab == -1) {
            tabPanel.addTab(PenilaianPanel.PANEL_NAME, PenilaianPanel.getPanel());
            setSelectedPanel(PenilaianPanel.PANEL_NAME);
        } else {
            tabPanel.setSelectedIndex(indexTab);
        }
    }//GEN-LAST:event_mnuItemInputPenilaianActionPerformed

    private void mnuItemRekapPenilaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemRekapPenilaianActionPerformed
        GenerateRekapPanel.getPanel().setName(GenerateRekapPanel.PANEL_NAME);
        indexTab = getComponentIndexByName(GenerateRekapPanel.PANEL_NAME);
        if (indexTab == -1) {
            tabPanel.addTab(GenerateRekapPanel.PANEL_NAME, GenerateRekapPanel.getPanel());
            setSelectedPanel(GenerateRekapPanel.PANEL_NAME);
        } else {
            tabPanel.setSelectedIndex(indexTab);
        }
    }//GEN-LAST:event_mnuItemRekapPenilaianActionPerformed

    private void mnuItemManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemManagementActionPerformed
        ManagementPanel.getPanel().setName(ManagementPanel.PANEL_NAME);
        indexTab = getComponentIndexByName(ManagementPanel.PANEL_NAME);
        if (indexTab == -1) {
            tabPanel.addTab(ManagementPanel.PANEL_NAME, ManagementPanel.getPanel());
            setSelectedPanel(ManagementPanel.PANEL_NAME);
        } else {
            tabPanel.setSelectedIndex(indexTab);
        }
    }//GEN-LAST:event_mnuItemManagementActionPerformed

    private void mnuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemLogoutActionPerformed
        tabPanel.removeAll();
        this.dispose();
        Main.initLogin();
    }//GEN-LAST:event_mnuItemLogoutActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private absen.karyawan.ui.JImagePanel jImagePanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuData;
    private javax.swing.JMenuItem mnuItemInputPenilaian;
    private javax.swing.JMenuItem mnuItemJabatan;
    private javax.swing.JMenuItem mnuItemKaryawan;
    private javax.swing.JMenuItem mnuItemLogout;
    private javax.swing.JMenuItem mnuItemManagement;
    private javax.swing.JMenuItem mnuItemRekapPenilaian;
    private javax.swing.JMenu mnuPenilaian;
    private javax.swing.JTabbedPane tabPanel;
    // End of variables declaration//GEN-END:variables
}
