/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package absen.karyawan.ui;

import absen.karyawan.ui.panel.GenerateRekapPanel;
import absen.karyawan.ui.panel.JabatanPanel;
import absen.karyawan.ui.panel.KaryawanPanel;
import absen.karyawan.ui.panel.PenilaianPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author adi
 */
public class MainFrame extends javax.swing.JFrame {

    private Integer indexTab = -1;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(MainFrame.MAXIMIZED_BOTH);
    }
    
    public JTabbedPane getTabPanel() {
        return tabPanel;
    }
    
    private int getComponentIndexByName(String panelName) {
        return tabPanel.indexOfTab(panelName);
    }

    private void setSelectedPanel(String panelName) {
        tabPanel.setSelectedComponent(tabPanel.getComponentAt(getComponentIndexByName(panelName)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tabPanel = new javax.swing.JTabbedPane();
        jImagePanel1 = new absen.karyawan.ui.JImagePanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuItemLogout = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuItemKaryawan = new javax.swing.JMenuItem();
        mnuItemJabatan = new javax.swing.JMenuItem();
        mnuItemInputPenilaian = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuItemRekapPenilaian = new javax.swing.JMenuItem();
        mnuItemManagement = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Penilaian Karyawan");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RANCANGAN APLIKASI AHP");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PENILAIAN KARYAWAN di PT. X");

        javax.swing.GroupLayout jImagePanel1Layout = new javax.swing.GroupLayout(jImagePanel1);
        jImagePanel1.setLayout(jImagePanel1Layout);
        jImagePanel1Layout.setHorizontalGroup(
            jImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        jImagePanel1Layout.setVerticalGroup(
            jImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 182, Short.MAX_VALUE)
        );

        tabPanel.addTab("Beranda", jImagePanel1);

        jMenu1.setText("System");

        mnuItemLogout.setText("Logout");
        jMenu1.add(mnuItemLogout);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Data");

        mnuItemKaryawan.setText("Karyawan");
        mnuItemKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemKaryawanActionPerformed(evt);
            }
        });
        jMenu2.add(mnuItemKaryawan);

        mnuItemJabatan.setText("Jabatan");
        mnuItemJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemJabatanActionPerformed(evt);
            }
        });
        jMenu2.add(mnuItemJabatan);

        jMenuBar1.add(jMenu2);

        mnuItemInputPenilaian.setText("Penilaian");

        jMenuItem1.setText("Input Penilaian");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuItemInputPenilaian.add(jMenuItem1);

        mnuItemRekapPenilaian.setText("Rekap Penilaian");
        mnuItemRekapPenilaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemRekapPenilaianActionPerformed(evt);
            }
        });
        mnuItemInputPenilaian.add(mnuItemRekapPenilaian);

        jMenuBar1.add(mnuItemInputPenilaian);

        mnuItemManagement.setText("Management");
        jMenuBar1.add(mnuItemManagement);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPanel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemKaryawanActionPerformed
        KaryawanPanel.getPanel().setName(KaryawanPanel.PANEL_NAME);
        indexTab = getComponentIndexByName(KaryawanPanel.PANEL_NAME);
        if (indexTab == -1) {
            tabPanel.addTab(KaryawanPanel.PANEL_NAME, KaryawanPanel.getPanel());
            setSelectedPanel(KaryawanPanel.PANEL_NAME);
        } else {
            tabPanel.setSelectedIndex(indexTab);
        }
    }//GEN-LAST:event_mnuItemKaryawanActionPerformed

    private void mnuItemJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemJabatanActionPerformed
        JabatanPanel.getPanel().setName(JabatanPanel.PANEL_NAME);
        indexTab = getComponentIndexByName(JabatanPanel.PANEL_NAME);
        if (indexTab == -1) {
            tabPanel.addTab(JabatanPanel.PANEL_NAME, JabatanPanel.getPanel());
            setSelectedPanel(JabatanPanel.PANEL_NAME);
        } else {
            tabPanel.setSelectedIndex(indexTab);
        }
    }//GEN-LAST:event_mnuItemJabatanActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        PenilaianPanel.getPanel().setName(PenilaianPanel.PANEL_NAME);
        indexTab = getComponentIndexByName(PenilaianPanel.PANEL_NAME);
        if (indexTab == -1) {
            tabPanel.addTab(PenilaianPanel.PANEL_NAME, PenilaianPanel.getPanel());
            setSelectedPanel(PenilaianPanel.PANEL_NAME);
        } else {
            tabPanel.setSelectedIndex(indexTab);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnuItemRekapPenilaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemRekapPenilaianActionPerformed
        GenerateRekapPanel.getPanel().setName(GenerateRekapPanel.PANEL_NAME);
        indexTab = getComponentIndexByName(GenerateRekapPanel.PANEL_NAME);
        if (indexTab == -1) {
            tabPanel.addTab(GenerateRekapPanel.PANEL_NAME, GenerateRekapPanel.getPanel());
            setSelectedPanel(GenerateRekapPanel.PANEL_NAME);
        } else {
            tabPanel.setSelectedIndex(indexTab);
        }
    }//GEN-LAST:event_mnuItemRekapPenilaianActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private absen.karyawan.ui.JImagePanel jImagePanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu mnuItemInputPenilaian;
    private javax.swing.JMenuItem mnuItemJabatan;
    private javax.swing.JMenuItem mnuItemKaryawan;
    private javax.swing.JMenuItem mnuItemLogout;
    private javax.swing.JMenu mnuItemManagement;
    private javax.swing.JMenuItem mnuItemRekapPenilaian;
    private javax.swing.JTabbedPane tabPanel;
    // End of variables declaration//GEN-END:variables
}
