/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package absen.karyawan.dialog;

import absen.karyawan.Main;
import absen.karyawan.TableUtil;
import absen.karyawan.domain.Karyawan;
import absen.karyawan.tablemodel.KaryawanTableModel;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author adi
 */
public class KaryawanDialog extends javax.swing.JDialog {

    private List<Karyawan> karyawans;
    private Karyawan karyawan;
    
    /**
     * Creates new form KaryawanDialog
     */
    public KaryawanDialog() {
        super(new JFrame(), true);
        try {
            initComponents();
            karyawans = Main.getService().getAllKaryawan();
            setLocationRelativeTo(null);
            loadDataToTable();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(Main.getMainFrame(), ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public Karyawan showDialog(){
        setVisible(true);
        return karyawan;
    }
    
    public void loadDataToTable(){
        tblDialogKaryawan.setModel(new KaryawanTableModel(karyawans));
        TableUtil.initColumn(tblDialogKaryawan);
        tblDialogKaryawan.getSelectionModel().addListSelectionListener(new TableSelection());
    }
    
    private class TableSelection implements ListSelectionListener {
        @Override
        public void valueChanged(ListSelectionEvent e) {
            if (e.getValueIsAdjusting()) {
                return;
            }
            if (tblDialogKaryawan.getSelectedRow() >= 0) {
                karyawan = karyawans.get(tblDialogKaryawan.getSelectedRow());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDialogKaryawan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDialogKaryawan = new javax.swing.JTable();
        btnRefreshKaryawan = new javax.swing.JButton();
        btnOKDialogKaryawan = new javax.swing.JButton();
        btnCancelDialogKaryawan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lookup Karyawan");

        tblDialogKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDialogKaryawan.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblDialogKaryawan.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblDialogKaryawan);

        btnRefreshKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absen/karyawan/images/refresh.gif"))); // NOI18N
        btnRefreshKaryawan.setText("Refresh");
        btnRefreshKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshKaryawanActionPerformed(evt);
            }
        });

        btnOKDialogKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absen/karyawan/images/save.png"))); // NOI18N
        btnOKDialogKaryawan.setText("OK");
        btnOKDialogKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKDialogKaryawanActionPerformed(evt);
            }
        });

        btnCancelDialogKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absen/karyawan/images/close.gif"))); // NOI18N
        btnCancelDialogKaryawan.setText("Cancel");
        btnCancelDialogKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelDialogKaryawanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOKDialogKaryawan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelDialogKaryawan))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtDialogKaryawan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefreshKaryawan)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDialogKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefreshKaryawan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOKDialogKaryawan)
                    .addComponent(btnCancelDialogKaryawan))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnRefreshKaryawan, txtDialogKaryawan});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelDialogKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelDialogKaryawanActionPerformed
        karyawan = null;
        this.dispose();
    }//GEN-LAST:event_btnCancelDialogKaryawanActionPerformed

    private void btnOKDialogKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKDialogKaryawanActionPerformed
        if(karyawan!=null){
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(Main.getMainFrame(), "Tidak ada Data yang dipilih !");
        }
    }//GEN-LAST:event_btnOKDialogKaryawanActionPerformed

    private void btnRefreshKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshKaryawanActionPerformed
        try {
            karyawans = Main.getService().getKaryawanByNipAndNameLike(txtDialogKaryawan.getText());
            loadDataToTable();
            TableUtil.initColumn(tblDialogKaryawan);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(Main.getMainFrame(), ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRefreshKaryawanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelDialogKaryawan;
    private javax.swing.JButton btnOKDialogKaryawan;
    private javax.swing.JButton btnRefreshKaryawan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDialogKaryawan;
    private javax.swing.JTextField txtDialogKaryawan;
    // End of variables declaration//GEN-END:variables
}
