/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package absen.karyawan.ui.panel;

import absen.karyawan.Main;
import absen.karyawan.TableUtil;
import absen.karyawan.dialog.GantiJabatanDialog;
import absen.karyawan.domain.RekapNilai;
import absen.karyawan.tablemodel.RekapBulananTableModel;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.apache.commons.lang.StringUtils;
import org.joda.time.DateTime;

/**
 *
 * @author adi
 */
public class ManagementPanel extends javax.swing.JPanel {
    
    private static ManagementPanel panel;
    public static final String PANEL_NAME = "Management Panel";
    private RekapNilai rekapNilai;
    private List<RekapNilai> rekapNilais;

    /**
     * Creates new form GenerateRekapPanel
     */
    public ManagementPanel() {
        try {
            initComponents();
            String tahun = String.valueOf(new DateTime().getYear());
            String bulan = StringUtils.leftPad(String.valueOf(new Date().getMonth()+1), 2, "0");
            rekapNilais = Main.getService().getRekapNilai(bulan, tahun);
            tblRekap.setModel(new RekapBulananTableModel(rekapNilais));
            TableUtil.initColumn(tblRekap);
            rekapNilai=null;
            btnUbahJabatan.setEnabled(false);
            tblRekap.getSelectionModel().addListSelectionListener(new TableSelection());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(Main.getMainFrame(), ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public static ManagementPanel getPanel() {
        if(panel==null){
            panel = new ManagementPanel();
        }
        return panel;
    }
    
    private class TableSelection implements ListSelectionListener {

        @Override
        public void valueChanged(ListSelectionEvent e) {
            if (e.getValueIsAdjusting()) {
                return;
            }

            if (tblRekap.getSelectedRow() >= 0) {
                rekapNilai = rekapNilais.get(tblRekap.getSelectedRow());
                btnUbahJabatan.setEnabled(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUbahJabatan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRekap = new javax.swing.JTable();
        btnClose = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();

        btnUbahJabatan.setForeground(new java.awt.Color(0, 0, 0));
        btnUbahJabatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absen/karyawan/images/edit.gif"))); // NOI18N
        btnUbahJabatan.setText("Ubah Jabatan");
        btnUbahJabatan.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnUbahJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahJabatanActionPerformed(evt);
            }
        });

        tblRekap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRekap.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tblRekap);

        btnClose.setForeground(new java.awt.Color(0, 0, 0));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absen/karyawan/images/logout.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnPrint.setForeground(new java.awt.Color(0, 0, 0));
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absen/karyawan/images/print.png"))); // NOI18N
        btnPrint.setText("Print");
        btnPrint.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnUbahJabatan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnUbahJabatan)
                    .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnClose, btnUbahJabatan});

    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        Main.getMainFrame().getTabPanel().remove(this);
        panel = null;
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnUbahJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahJabatanActionPerformed
        Boolean sukses = new GantiJabatanDialog().showDialog(rekapNilai.getKaryawan());
        if(sukses){
            JOptionPane.showMessageDialog(Main.getMainFrame(), "Sukses Ubah jabatan !", "Info", JOptionPane.INFORMATION_MESSAGE);
            tblRekap.setModel(new RekapBulananTableModel(rekapNilais));
            TableUtil.initColumn(tblRekap);
        }
    }//GEN-LAST:event_btnUbahJabatanActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnUbahJabatan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRekap;
    // End of variables declaration//GEN-END:variables
}
